### ISSUE TITLE
What is required for the "core" package?

### ISSUE THREAD

**Issue by eddieajau** [joomla-cms/start-here#3]
I preempting the idea that there will be at least a stripped down "core" package that would be the basic "thing" you could install and still be called "Joomla" (though possibly not yet a "CMS").

What are the minimum set of existing extensions that we need for the "core" package?

**Comment by bweston92** [comment]
Any updates to this?

**Comment by Bakual** [comment]
Na, this repo basically should be deleted.

**Comment by bweston92** [comment]
So we're not going to go for a decent setup for developers? :D

**Comment by infograf768** [comment]
Anything "decent" these days?
:joy:

**Comment by Bakual** [comment]
Further decoupling (beysond weblinks) is on hold for now.
